version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: react-infinite-scroll-component
    versions:
    - 6.0.0
  - dependency-name: react-scripts
    versions:
    - 4.0.2
